services:
  app:
    container_name: academic-app
    build: .
    volumes:
      - ./writable:/var/www/html/writable
      - ./public/uploads:/var/www/html/public/uploads
    ports:
      - "80:80"
    environment:
      - APP_NAME=ProttashaAcademic
      - CI_ENVIRONMENT=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
